VERSION=0.1.6
LDFLAGS=-ldflags "-w -s -X main.version=${VERSION}"
all: check lint bench

.PHONY: check lint bench

check: *.go
	go test -v ./...
	go test -race ./...

lint:
	golangci-lint run --timeout 5m ./...

bench: *.go
	go test -run='^$$' -bench=BenchmarkSortDistributions -benchmem -benchtime=2ms ./...
	go test -run='^$$' -bench=BenchmarkSampdoAll -benchmem -benchtime=100ms ./...