VERSION=0.0.3
all: check lint bench

.PHONY: check lint bench

check: *.go
	go test -v ./...
	go test -race ./...
	go test -tags=purego ./...

lint:
	golangci-lint run --timeout 5m ./...

bench: *.go
	go test -run='^$$' -bench=BenchmarkSortDistributions -benchmem -benchtime=2ms ./...
	go test -run='^$$' -bench=BenchmarkSampdoAll -benchmem -benchtime=100ms ./...